### ISSUE TITLE
Feature request; support downloading files

### ISSUE THREAD

**Issue by krzkaczor** [dethcrypto/ethereum-code-viewer#47]
https://twitter.com/elyx0/status/1491682636955369474?s=21

**Comment by Elyx0** [comment]
Bumping since I retried recently:

```
 WARN DOMException: Failed to execute 'showDirectoryPicker' on 'Window': Cross origin sub frames aren't allowed to show a file picker.
    at B.i (https://code.deth.net/out/vs/workbench/workbench.web.main.js:2551:118413)
    at async B.h (https://code.deth.net/out/vs/workbench/workbench.web.main.js:2551:118137)
 ```

Same on Edge.
